### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Araara7** [datpt1603/air-moonbix#1]
![image](https://github.com/user-attachments/assets/595e98de-1605-4b5a-8739-39ccb54b977f)

**Comment by datpt1603** [comment]
We apologize for the inconvenience, but due to a high volume of users on our Telegram mini app, the system is currently experiencing some instability. Please try again later.

**Comment by datpt1603** [comment]
@Araara7 Binace's mini app is currently having problems, so please try again later
